client_id = "d99f8bbe7d0eb2cf598b442bd7b83b38"

name = "product-export-production"
handle = "product-export-prod"
application_url = "https://ilf-product-export-embeded.onrender.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://ilf-product-export-embeded.onrender.com/auth/callback",
  "https://ilf-product-export-embeded.onrender.com/api/auth/callback",
  "https://ilf-product-export-embeded.onrender.com/auth/shopify/callback"
]
[pos]
embedded = false


