# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fe5c072c330e1f66b3cb33d90b0aa0c2"
name = "Product-export-app"
application_url = "https://jellyfish-app-3qksh.ondigitalocean.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_products,read_inventory,read_publications,read_locations"

[auth]
redirect_urls = [
  "https://jellyfish-app-3qksh.ondigitalocean.app/auth/callback",
  "https://jellyfish-app-3qksh.ondigitalocean.app/auth/shopify/callback",
  "https://ilf-oauth-middleware-vn4rm.ondigitalocean.app/auth/shopify/callback"
]

[pos]
embedded = false
